name: Subkari
channels:
  - anaconda
  - defaults
dependencies:
  - aom=3.6.0=hd77b12b_0
  - blinker=1.9.0=py312haa95532_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - click=8.2.1=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - expat=2.7.1=h8ddb27b_0
  - flask=3.1.2=py312haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icu=73.1=h6c2663c_0
  - itsdangerous=2.2.0=py312haa95532_0
  - jinja2=3.1.6=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.1.1=h827c3e9_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libopenjpeg=2.5.4=h02ab6af_0
  - libpng=1.6.50=h46444df_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - openjpeg=2.5.4=h56d5a42_0
  - openssl=3.0.18=h543e019_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.3.0=py312hb328d1f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - python=3.12.2=h1d929f7_0
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - werkzeug=3.1.3=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - datetime==5.5
      - flask-cors==6.0.1
      - idna==3.11
      - mysql-connector==2.2.9
      - pytz==2025.2
      - requests==2.32.5
      - urllib3==2.5.0
      - zope-interface==8.0.1
prefix: C:\Users\masaya\anaconda3\envs\Subkari
